#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (FPV Cam)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10015_gazebo-classic_iris

# No GPS
param set-default SYS_HAS_GPS 0
param set-default EKF2_GPS_CTRL 0
param set-default EKF2_HGT_REF 0
param set-default COM_ARM_WO_GPS 1

# Magnetometer heading (no WMM without GPS)
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_MAG_CHECK 0
