#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (FPV Cam)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10015_gazebo-classic_iris

# Disable GPS
# param set-default EKF2_GPS_CTRL 0

# Use barometer for height (default=1/GPS, won't work with GPS disabled)
# param set-default EKF2_HGT_REF 0

# Allow arming without GPS position
# param set-default COM_ARM_WO_GPS 1
