#!/bin/sh
#
# @name My Tailsitter (gz-sim, quadrotor "+" mode)
#
# @type Quadrotor +
# @class Copter
#
# @maintainer Ilya
#
# @board px4_sitl exclude
#
# This airframe brings up the my_tailsitter Gazebo model and flies it
# as a quadrotor "+" until you wire up the VTOL tailsitter transition.
#
# Rotor order matches model.sdf:
#   motor 0  +X  CCW
#   motor 1  +Y  CW
#   motor 2  -X  CCW
#   motor 3  -Y  CW

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=my_tailsitter}

param set-default SIM_GZ_EN 1

# --- Airframe geometry: quadrotor + ---
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Rotor 0  @  +X, CCW
param set-default CA_ROTOR0_PX  0.223
param set-default CA_ROTOR0_PY  0.0
param set-default CA_ROTOR0_PZ -0.127     # PX4 body frame is FRD (Z down)
param set-default CA_ROTOR0_KM  0.05      # CCW = positive moment coefficient
# Rotor 1  @  +Y, CW
param set-default CA_ROTOR1_PX  0.0
param set-default CA_ROTOR1_PY  0.223
param set-default CA_ROTOR1_PZ -0.127
param set-default CA_ROTOR1_KM -0.05
# Rotor 2  @  -X, CCW
param set-default CA_ROTOR2_PX -0.223
param set-default CA_ROTOR2_PY  0.0
param set-default CA_ROTOR2_PZ -0.127
param set-default CA_ROTOR2_KM  0.05
# Rotor 3  @  -Y, CW
param set-default CA_ROTOR3_PX  0.0
param set-default CA_ROTOR3_PY -0.223
param set-default CA_ROTOR3_PZ -0.127
param set-default CA_ROTOR3_KM -0.05

# --- Output mapping: motors 1..4 on SIM_GZ_ACTUATOR_FUNC1..4 ---
param set-default SIM_GZ_EC_FUNC1 101   # Motor 1 -> CA_ROTOR0
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN1  100
param set-default SIM_GZ_EC_MIN2  100
param set-default SIM_GZ_EC_MIN3  100
param set-default SIM_GZ_EC_MIN4  100
param set-default SIM_GZ_EC_MAX1  1000
param set-default SIM_GZ_EC_MAX2  1000
param set-default SIM_GZ_EC_MAX3  1000
param set-default SIM_GZ_EC_MAX4  1000

# --- Mass / dynamics tuning placeholders (replace with measured values) ---
param set-default MPC_THR_HOVER  0.50      # 50% throttle for hover
param set-default MC_ROLLRATE_P  0.15
param set-default MC_PITCHRATE_P 0.15
param set-default MC_YAWRATE_P   0.20

# --- Battery (placeholder: 4S Li-Po, 5000 mAh) ---
param set-default BAT1_N_CELLS 4
param set-default BAT1_CAPACITY 5000
